### ISSUE TITLE
[Feature] Zoom/Scale behavior

### ISSUE THREAD

**Issue by benjamindulau** [lifelynl/focuspoint#2]
Hey,

Did you consider adding a "zoom/scale" behavior in addition of the focus point? So we can both crop and get a focus point, all in one operation.

How would you do it?

**Comment by jessedvrs** [comment]
The problem with zooming/re-scaling is that, in the eyes of the user, the desired zoom level will always depend on the size and aspect-ratio of the canvas of the editor. For example, when the editor is small, the user will zoom in further to get a better display of the picture. When the editor-canvas is large, the user won't.

This is contradictory to the problem this package is solving; we want a universal/canvas-independent point of focus to be able to display the image properly in every aspect-ratio.

Do you agree on this?

**Comment by renaudkaczmarek** [comment]
Hi Jessedvrs !

I'm working with Benjamin on this :)

I don't think it's contradictory. In fact, we need to be able to zoom in the background-size:cover.
I don't see any other solution than using a wrapper inside a container with an overflow:hidden; and some mathematic magic transform ! (Sorry for my english :p)

``` html
<div class="container" style="overflow:hidden"> 
   <div class="wrapper" 
        style="
                   background-size:cover; 
                   background-position: X% Y%; 
                   transform: scale(S) translateX(X/S) translateY(Y/S);">
    </div>
</div>

```

I know this will not work properly with this but I don't know why I'm sure it's something doable...

**Comment by jessedvrs** [comment]
Hey renaudkaczmarek,

Zooming/scaling (as well as rotating and other image effects) are one-time jobs, which means the images should be _saved_ on the server like that instead of applying those effects browser-side, every time again. Sure there are CSS tricks to do it, but I would strongly discourage using them. It would be browser-heavy and unnecessary.

The focuspoint, on the other hand, depends on the aspect-ratio of the canvas. So probably every rendering situation is different. For the focuspoint there's no other way then to calculate it browser-side.

Besides, this package is called focuspoint because it only deals with the point of focus. So let's keep this package small, solving one problem only.

**Comment by jessedvrs** [comment]
If you really need to be able to change the background-size (for example to slightly zoom the picture on mouseover), then I would recommend doing something like this:

``` html
<figure>
  <div class="image"></div>
</figure>
```

``` css
figure {
  width: 400px;
  height: 400px;
  overflow: hidden;
}

.image {
  width: 100%;
  height: 100%;
  background-image: url('http://lorempixel.com/output/nature-q-c-764-564-8.jpg');
  background-size: cover;
  background-position: 33% 50%; /* Some focuspoint */
  transition: transform .15s;
}

.image:hover {
  transform: scale(1.05);
}
```

Codepen: http://codepen.io/anon/pen/XmbmdY
